import '@components/baron';
import '@components/burger';
import '@components/field-file';
import '@components/field-num';
import '@components/field-text';
import '@components/field-select';
import '@components/form-validation';
import '@components/main-nav';
import '@components/off-canvas';
import '@components/scroll-link';
import '@components/sprite-svg';
import '@components/tabs';
import '@components/to-top';
import '@components/modal';
import '@components/slider';
import '@components/dynamic-adapt';
import '@components/accordion';
import '@components/mobile-menu';

document.documentElement.classList.remove('no-js');
document.documentElement.classList.add('js');
